# docker-compose.yml
version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-telegram-alerts
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-telegram_alerts}
      MYSQL_USER: ${DB_USER:-appuser}
      MYSQL_PASSWORD: ${DB_PASS:-apppass}
    ports:
      - "${DB_PORT:-3307}:3306"
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-character-set-client-handshake"
      - "--init-connect=SET NAMES utf8mb4"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    image: telegram-alert:1.0.0
    container_name: telegram-alert-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Spring datasource 指向 service 名稱 db:3306（容器內）
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE:-telegram_alerts}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Taipei
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-appuser}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS:-apppass}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

      # App 自己的環境變數
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_IDS: ${TELEGRAM_CHAT_IDS:-"-4887343110"}
      ALERTS_API_KEY: ${ALERTS_API_KEY:-alert-key}
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  dbdata:
