server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3307/telegram_alerts?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8mb4&serverTimezone=Asia/Taipei
    username: ${DB_USER:appuser}
    password: ${DB_PASS:apppass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: Asia/Taipei

management:
  endpoints:
    web:
      exposure:
        include: health,info

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-ids: ${TELEGRAM_CHAT_IDS:- -1001234567890}
  parse-mode: HTML
  disable-web-page-preview: true
  disable-notification: false
  api-url: https://api.telegram.org

security:
  api-key: ${ALERTS_API_KEY:change-me}
