# application.yml
server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    # 本機（不跑 Docker）時的預設：指向本機 3307，和 compose 對外埠一致
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:${DB_PORT:3307}/${MYSQL_DATABASE:telegram_alerts}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei}
    username: ${SPRING_DATASOURCE_USERNAME:appuser}
    password: ${SPRING_DATASOURCE_PASSWORD:apppass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
    show-sql: true

# ✅ 和 TelegramProperties(prefix="telegram") 對齊：沒有中間那層 "bot"
telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-ids: ${TELEGRAM_CHAT_IDS}

# ✅ 和你 ApiKeyAuthFilter 讀的 key 對齊（之前你用 ALERTS_API_KEY）
security:
  api-key: ${ALERTS_API_KEY:alert-key}
